# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DiplomadoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DiplomadoApp
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  
  target 'DiplomadoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DiplomadoAppUITests' do
    # Pods for testing
  end

end
